---
- name: Deploy OpenCARWINGS
  hosts: carwings
  become: true

  vars:
    # Required variables to change before first deployment.
    opencarwings_db_password: "CHANGE_ME_DB_PASSWORD"
    opencarwings_domain: "CHANGE_ME_DOMAIN"
    opencarwings_letsencrypt_email: "CHANGE_ME_EMAIL"
    opencarwings_cloudflare_api_token: "CHANGE_ME_CLOUDFLARE_TOKEN"
    opencarwings_django_secret_key: "CHANGE_ME_DJANGO_SECRET_KEY"
    opencarwings_signup_enabled: true
    opencarwings_smsapi_base_url: "http://smsapi:8000"
    opencarwings_smsapi_timeout: "10"

  roles:
    - role: opencarwings
